#!/usr/bin/env bash

tmp=$(mktemp -p "$TMPDIR" "gitlog.XXXXXXXXX")

superlog()
{
    find "${@:-.}" -type d -name .git -execdir bash -c 'git log --all --pretty="tformat:%as "$(basename "$PWD")" %h %s  [%aN]"' \; > "$tmp"
}

superlog | sort -r > "$tmp"

cat "$tmp" | cut -d ' ' -f 2 | sort -u | xargs -I{} /usr/bin/grep -m 1 "\d\d\d\d\-\d\d\-\d\d {} " "$tmp" | sort -r | less

rm "$tmp"
